name: Cross Packaging

on:
  push:
    tags:
      - '**'

jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Dependencies
        run: corepack enable && yarn
      - name: Rebuild Natives
        run: yarn electron-rebuild
      - name: Build
        run: yarn bundle-all && yarn make-release -l && yarn make-debug -l && yarn make-autotest -l
      - uses: actions/upload-artifact@v3
        with:
          name: Linux Packages
          path: |
            ./dist/release/*.tar.xz
            ./dist/release/*.deb
            ./dist/release/*.rpm
            ./dist/debug/*.zip
            ./dist/autotest/*.zip

  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Dependencies
        run: corepack enable && yarn
      - name: Rebuild Natives
        run: yarn electron-rebuild
      - name: Build
        run: yarn bundle-all && yarn make-release -w && yarn make-debug -w && yarn make-autotest -w
      - uses: actions/upload-artifact@v3
        with:
          name: Windows Packages
          path: |
            ./dist/release/*.exe
            ./dist/release/*.zip
            ./dist/debug/*.zip
            ./dist/autotest/*.zip

  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Dependencies
        run: corepack enable && yarn
      - name: Rebuild Natives
        run: yarn electron-rebuild
      - name: Build
        run: yarn bundle-all && yarn make-release -m && yarn make-debug -m && yarn make-autotest -m
      - uses: actions/upload-artifact@v3
        with:
          name: macOS Packages
          path: |
            ./dist/release/*.dmg
            ./dist/release/*.zip
            ./dist/debug/*.zip
            ./dist/autotest/*.zip
