name: Cross Packaging

on:
  push:
    branches: [ main ]

jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i
      - name: Rebuild Natives
        run: pnpm electron-rebuild
      - name: Build
        run: pnpm bundle-release && pnpm make-release -l
      - name: List Files
        run: ls ./dist/release

  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i
      - name: Rebuild Natives
        run: pnpm electron-rebuild
      - name: Build
        run: pnpm bundle-release && pnpm make-release -w
      - name: List Files
        run: ls ./dist/release

  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i
      - name: Rebuild Natives
        run: pnpm electron-rebuild
      - name: Build
        run: pnpm bundle-release && pnpm make-release -m
      - name: List Files
        run: ls ./dist/release
