# This is REALLY SLOW!

name: Cross Packaging

on:
  push:
    branches: [ main ]

jobs:
  package-unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: corepack enable
      - run: yarn
      - run: yarn bundle-release
      - run: yarn make-release -l

  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: corepack enable
      - run: yarn
      - run: yarn bundle-release
      - run: yarn make-release -w

  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: corepack enable
      - run: yarn
      - run: yarn bundle-release
      - run: yarn make-release -m
