name: Autotest

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
      - name: Build
        run: pnpm i && pnpm electron-rebuild && pnpm bundle-autotest
      - name: Test
        run: pnpm test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
      - name: Build
        run: pnpm i && pnpm electron-rebuild && pnpm bundle-autotest
      - name: Test
        run: pnpm test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: pnpm
      - name: Setup xvfb
        run: sudo apt install xvfb
      - name: Build
        run: pnpm i && pnpm electron-rebuild && pnpm bundle-autotest
      - name: Test
        run: xvfb-run pnpm test
