name: Autotest Full

on:
  push:
    tags:
      - '**'

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build
        run: corepack enable && yarn && yarn electron-rebuild && yarn bundle-autotest
      - name: Test
        run: yarn test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build
        run: corepack enable && yarn && yarn electron-rebuild && yarn bundle-autotest
      - name: Test
        run: yarn test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Setup xvfb
        run: sudo apt install xvfb
      - name: Build
        run: corepack enable && yarn && yarn electron-rebuild && yarn bundle-autotest
      - name: Test
        run: xvfb-run yarn test
